#version of docker compose
version: '3'
services:
  web:
    #image: furyanaor/dev8200-startproj_web:latest
    build: .
    ports:
      - "7007:80"
    volumes:
      - .:/code
  mysqldb:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  phpmyadmin:
    image: phpmyadmin:5.1-apache
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysqldb
  prometheus:
    image: prom/prometheus:latest
    # volumes:
    #         - /grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:80
  grafana:
    image: grafana/grafana:latest
    # volumes:
    #         - /grafana/grafana.ini:/etc/grafana/grafana.ini
    #         - /grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:80
    links:
            - prometheus