#version of docker compose
version: '3'
services:
  web:
    #image: furyanaor/dev8200-startproj_web:latest
    build: .
    ports:
      - "7007:80"
    volumes:
      - .:/code
  mysqldb:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  phpmyadmin:
    image: phpmyadmin:5.1-apache
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysqldb
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"    